### ISSUE TITLE
exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by balajimore** [corda/corda-docker#23] opened 2018-07-24 13:36 UTC
Steps:
1. Create `Dockerfile` for nodes by running Gradle task.
2. Build docker image using docker-compose or single image for a specific node.
3. Run an image that just created, docker throws below error:
``` standard_init_linux.go:190: exec user process caused "no such file or directory" ```

After some trial I just updated below line in `run-corda.sh` and container staterted successfully:
From: ` java $JAVA_OPTIONS -jar ${CORDA_HOME}/corda.jar 2>&1 `
To: ` java ${JAVA_OPTIONS} -jar ${CORDA_HOME}/corda.jar 2>&1`

I have little knowledge of docker but don't know why that error was. 
Also, I don't think there is any wrong with the original `run-corda.sh` file.

**Comment by Koshub** [comment] 2018-10-04 07:11
👍

**Comment by Koshub** [comment] 2018-10-04 08:10
Probably duplicate of https://github.com/corda/corda/issues/3961

**Comment by wawrzek** [comment] 2018-12-07 11:53
Please check new docker build from main corda repository: https://github.com/corda/corda/tree/master/docker

**Closed by wawrzek** 2018-12-07 11:53 UTC
